name: decompile

on:
  workflow_dispatch:

jobs:
  decompile:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: ensure repository visibility is private
        if: ${{ !github.event.repository.private }}
        run: echo "please change repository visibility to private" && exit 1

      - name: fetch decompiler
        run: git clone --depth=1 'https://github.com/SpaceEngineersCommunity/decompiler'

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '>= 3.11'

      - name: set up python dependencies
        run: pip install -r decompiler/requirements.txt

      - name: setup dotnet 9 for decompiler
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9

      - name: setup dotnet 10 for ILSpy
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10
          dotnet-quality: preview

      - name: setup ILSpy
        run: |
          git clone --depth=1 'https://github.com/icsharpcode/ILSpy'
          cd ILSpy
          sed -i 's/sortCustomAttributes = false/sortCustomAttributes = true/' ICSharpCode.Decompiler/DecompilerSettings.cs
          dotnet build --configuration Release ICSharpCode.ILSpyCmd/ICSharpCode.ILSpyCmd.csproj
          echo $PWD/ICSharpCode.ILSpyCmd/bin/Release/*/ >> "$GITHUB_PATH"

      - name: setup .NET Framework
        run: |
          curl -Lo net48.zip 'https://www.nuget.org/api/v2/package/Microsoft.NETFramework.ReferenceAssemblies.net48/1.0.3'
          unzip net48.zip -d net48

      - name: setup DepotDownloader
        run: |
          mkdir depotdownloader
          cd depotdownloader
          url=$(curl -s 'https://api.github.com/repos/SteamRE/DepotDownloader/releases/latest' | sed -n 's/.*"\(.*-linux-x64.zip\)"$/\1/p')
          curl -Lo depotdownloader.zip "$url"
          unzip depotdownloader.zip

      - name: download Space Engineers Dedicated binaries
        run: |
          echo 'regex:^DedicatedServer64/' > filelist.txt
          depotdownloader/DepotDownloader -app 298740 -depot 298741 -filelist filelist.txt -dir .

      - name: checkout
        uses: actions/checkout@v4
        with:
          path: repo

      - name: decompile
        run: |
          cd repo
          ../decompiler/decompile.py \
            --netframework ../net48/build/.NETFramework/v4.8 \
            --file ../DedicatedServer64/SpaceEngineersDedicated.exe \
            --file ../DedicatedServer64/SpaceEngineersDedicatedUpdater.exe \
            --file ../DedicatedServer64/VRageRemoteClient.exe

      - name: push
        run: |
          cd repo
          git config user.name 'decompiler'
          git config user.email 'no@email'
          git add .
          git commit -m 'decompiled'
          git push
